version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci:"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "release-22.05"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci:"
